# Generated by Django 5.2.14 on 2026-05-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_confirmed', 'Booking Confirmed'), ('payment_received', 'Payment Received'), ('service_order_confirmed', 'Service Order Confirmed'), ('room_ready', 'Room Ready'), ('password_reset', 'Password Reset')], max_length=30),
        ),
    ]
