# Generated by Django 5.2.14 on 2026-05-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_services', '0005_add_old_confirmed_services_to_booking'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE hotel_service_order DROP COLUMN IF EXISTS is_amount_added_to_booking;",
            reverse_sql="ALTER TABLE hotel_service_order ADD COLUMN is_amount_added_to_booking BOOLEAN DEFAULT FALSE;",
        ),
    ]
