# Generated by Django 5.2.14 on 2026-05-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_gateway_meta_payment_vnp_transaction_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_url',
            field=models.URLField(blank=True, default='', max_length=2000),
        ),
    ]
